backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: 'posts/media'
public_folder: '../media'

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog Entries'
    label_singular: 'Blog Entry'
    description: 'Write a blog entry.'
    folder: 'posts/entries'
    create: true
    delete: false
    extension: 'md'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Path',
          name: 'path',
          widget: 'string',
          default: '/blog/new-post',
        }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'post' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    editor:
      preview: false
